PR for Bookstore Demo Theme
bmoreonrails/bookstore pull request #1
Opened 2016-12-19 14:32 UTC by aclarkk

@alimi take a look at this theme, should be ready to pull in. Let me know if you need any changes.

2016-12-20 03:35 UTC, alimi requested changes
This looks pretty good. I left some feedback to clean up some spacing/indentation to keep the code consistent throughout the app.

Thanks again @aclarkk 🙇🏾

2016-12-20 03:35 UTC, alimi commented on app/views/books/index.html.erb
> +<%= link_to 'Add a book', new_book_path, class: "button" %>
Can you nest this link back inside the `if`?

2016-12-20 03:35 UTC, alimi commented on app/assets/stylesheets/application.scss
> +		&:hover{
There are a few spots throughout the file where the indentation is off. Can you clean it up so the file looks more consistent?

2016-12-20 03:35 UTC, alimi commented on app/views/books/show.html.erb
> +    <%= link_to 'Edit Book', edit_book_path(@book), class: "button" %>
Can you remove the two extra spaces that were added to the beginning of each line inside the `if`?

2016-12-20 03:35 UTC, alimi commented on app/views/layouts/application.html.erb
> +    <div class="navigation">
Can you update this file so we're using two spaces per line indent?

2016-12-20 03:40 UTC, jgaskins commented on app/assets/stylesheets/application.scss
> +		&:hover{
Dem tabs, tho

2016-12-23 00:45 UTC, clickclickonsal commented on app/assets/stylesheets/application.scss
> +		&:hover{
Spaces > Tabs

2016-12-30 16:55 UTC, merged

2016-12-30 16:56 UTC, alimi commented
@aclarkk I went ahead and updated the spacing stuff.

![b48](https://cloud.githubusercontent.com/assets/772925/21569006/fa85da08-ce86-11e6-8a42-6a9a10d8f310.gif)